version: '3.8'

services:
  gpt-pilot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/amd64
    container_name: gpt-pilot
    restart: unless-stopped
    
    ports:
      - "8125:8125"
      - "8222:8222"
      - "8080:8080"
      - "3000:3000"
      - "5173:5173"
    
    volumes:
      - ./workspace:/pythagora/pythagora-core/workspace
      - ./data:/pythagora/pythagora-core/data
      - ./config.json:/pythagora/pythagora-core/config.json:ro
      - ./logs:/pythagora/pythagora-core/logs
    
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PYTHAGORA_DATA_DIR=/pythagora/pythagora-core/data
      - TZ=Europe/Paris
    
    networks:
      - gpt-pilot-network
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gpt-pilot.rule=Host(`gpt-pilot.yourdomain.com`)"
      - "traefik.http.routers.gpt-pilot.entrypoints=websecure"
      - "traefik.http.routers.gpt-pilot.tls.certresolver=letsencrypt"
      - "traefik.http.services.gpt-pilot.loadbalancer.server.port=8080"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Reverse Proxy avec Traefik (optionnel)
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"  # Dashboard Traefik
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/config:/config:ro
    
    networks:
      - gpt-pilot-network
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.yourdomain.com`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"

  # Monitoring avec Prometheus (optionnel)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    
    ports:
      - "9090:9090"
    
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    
    networks:
      - gpt-pilot-network

  # Visualisation avec Grafana (optionnel)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    
    ports:
      - "3001:3000"
    
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    
    networks:
      - gpt-pilot-network
    
    depends_on:
      - prometheus

networks:
  gpt-pilot-network:
    driver: bridge

volumes:
  workspace:
    driver: local
  data:
    driver: local
  logs:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
